const NOTIFICATION_TYPES = Object.freeze({
  TICKET_CREATED: "TICKET_CREATED",
  TICKET_ASSIGNED: "TICKET_ASSIGNED",
  TICKET_REASSIGNED: "TICKET_REASSIGNED",
  TICKET_UNASSIGNED: "TICKET_UNASSIGNED",
  STATUS_CHANGED: "STATUS_CHANGED",
  PRIORITY_CHANGED: "PRIORITY_CHANGED",
  PUBLIC_COMMENT: "PUBLIC_COMMENT",
  INTERNAL_NOTE: "INTERNAL_NOTE",
  TICKET_RESOLVED: "TICKET_RESOLVED",
  TICKET_REOPENED: "TICKET_REOPENED",
  TICKET_CLOSED: "TICKET_CLOSED",
  SLA_WARNING: "SLA_WARNING",
  SLA_BREACHED: "SLA_BREACHED",
});

module.exports = { NOTIFICATION_TYPES };
