const router = require("express").Router();
const authenticate = require("../../middleware/authenticate");
const authorizeRoles = require("../../middleware/authorize");
const validate = require("../../middleware/validate");
const { USER_ROLES } = require("../../constants/roles");
const { reportQueryValidation, dateRangeValidation, technicianPerformanceValidation } = require("./reports.validation");
const { getTicketReport, getDateRangeReport, getTechnicianPerformanceReport } = require("./reports.controller");
router.use(authenticate, authorizeRoles(USER_ROLES.ADMIN));
router.get("/tickets", reportQueryValidation(), validate, getTicketReport);
router.get("/date-range", dateRangeValidation, validate, getDateRangeReport);
router.get("/technician-performance", technicianPerformanceValidation, validate, getTechnicianPerformanceReport);
module.exports = router;
