const router = require("express").Router();
const authenticate = require("../../middleware/authenticate");
const authorizeRoles = require("../../middleware/authorize");
const validate = require("../../middleware/validate");
const { USER_ROLES } = require("../../constants/roles");
const { ticketCsvValidation, ticketReportValidation, dateRangeValidation, technicianPerformanceValidation, slaReportValidation, categoryReportValidation, priorityReportValidation, statusReportValidation } = require("./reports.validation");
const { exportTicketPdf, exportDateRangeCsv, exportTechnicianPerformanceCsv, exportSlaCsv, exportCategoryCsv, exportPriorityCsv, exportStatusCsv, exportTicketCsv, getTicketReport, getDateRangeReport, getTechnicianPerformanceReport, getSlaReport, getCategoryReport, getPriorityReport, getStatusReport } = require("./reports.controller");
router.use(authenticate, authorizeRoles(USER_ROLES.ADMIN));
router.get("/tickets/export/pdf", ticketCsvValidation, validate, exportTicketPdf);
router.get("/tickets/export/csv", ticketCsvValidation, validate, exportTicketCsv);
router.get("/tickets", ticketReportValidation, validate, getTicketReport);
router.get("/date-range", dateRangeValidation, validate, getDateRangeReport);
router.get("/technician-performance", technicianPerformanceValidation, validate, getTechnicianPerformanceReport);
router.get("/sla", slaReportValidation, validate, getSlaReport);
router.get("/categories", categoryReportValidation, validate, getCategoryReport);
router.get("/priorities", priorityReportValidation, validate, getPriorityReport);
router.get("/statuses", statusReportValidation, validate, getStatusReport);
router.get("/date-range/export/csv", dateRangeValidation, validate, exportDateRangeCsv);
router.get("/technician-performance/export/csv", technicianPerformanceValidation, validate, exportTechnicianPerformanceCsv);
router.get("/sla/export/csv", slaReportValidation, validate, exportSlaCsv);
router.get("/categories/export/csv", categoryReportValidation, validate, exportCategoryCsv);
router.get("/priorities/export/csv", priorityReportValidation, validate, exportPriorityCsv);
router.get("/statuses/export/csv", statusReportValidation, validate, exportStatusCsv);
module.exports = router;
